create database customer_behaviour;
use customer_behaviour;
select * from customer_shopping_behaviour;

-- 1. What is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue
from customer_shopping_behaviour
group by gender;

-- 2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer_shopping_behaviour
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer_shopping_behaviour);

  
-- 3. Which are the top 5 products with the highest average review rating?
select item_purchased as product,round(avg(review_rating),2) as avg_rating
from customer_shopping_behaviour
group by product
order by avg_rating desc limit 5;

-- 4. Compare the average purchase amounts between Standard and Express Shipping.
select shipping_type, round(avg(purchase_amount),2) as avg_purchase_amount
from customer_shopping_behaviour
group by shipping_type
having shipping_type in ('Standard','Express');


-- 5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers
select * from customer_shopping_behaviour;
select subscription_status,count(customer_id) as total_customers,round(avg(purchase_amount),2) as avg_spend,sum(purchase_amount) as total_revenue
from customer_shopping_behaviour
group by subscription_status
order by avg_spend desc;

-- 6. Which products have the highest percentage of purchases with discounts applied?

select item_purchased as product,
round(100* sum(case when discount_applied ='yes' then 1 else 0 end)/count(*),2)as with_discount_purchase_percentage
from customer_shopping_behaviour
group by product
order by with_discount_purchase_percentage desc;

-- 7. Segment customers into New, Returning and Loyal based on their total number of previous purchases and show the count of each segment.

with customer_type as(select
customer_id,previous_purchases,
case when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customer_shopping_behaviour)
select customer_segment,count(*) as 'Number of customers'
from customer_type
group by customer_segment;


-- 8. What are the top 3 most puchased products within each category?
with ranked_products as (select item_purchased as product, category, count(*) as purchase_count,row_number() over (partition by category order by count(*) desc) product_rank
from customer_shopping_behaviour
group by product,category)

select product_rank,category,product,purchase_count
from ranked_products
where product_rank<=3 ;

-- 9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status,count(customer_id)as repeat_buyers
from customer_shopping_behaviour
where previous_purchases>5
group by subscription_status;

-- 10. What is the revenue contribution of each age group?
select age_group,sum(purchase_amount) as revenue
from customer_shopping_behaviour
group by age_group
order by revenue desc;